CREATE DATABASE forum CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE forum;

CREATE TABLE utilisateur (
  id INT(3) NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  mdp VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE react (
  id_like INT(3) NOT NULL AUTO_INCREMENT,
  id_user INT(3) NOT NULL,
  id_post INT(3) NOT NULL,
  PRIMARY KEY (id_like)
) ENGINE=INNODB;

CREATE TABLE post (
  id_post INT(3) NOT NULL AUTO_INCREMENT,
  content VARCHAR(255) NOT NULL,
  PRIMARY KEY (id_post)
) ENGINE=INNODB;